/**
 * grafit/core entry point: the engine without a single series/axis module.
 * Modules are wired up explicitly: import from 'grafit-charts/modules' + register().
 * Tree-shaking drops everything that is not registered.
 */
import { buildCharts } from '@/app/chart-factory';

export const Charts = buildCharts();

export { register } from '@/app/registry';
export type {
  ChartModule,
  SeriesModule,
  AxisModule,
  TooltipContentData,
  TooltipHeading,
  TooltipRow,
  NodeRef,
  SelectedNode,
  ImperativeOptions,
  DomainAnchor,
  ZoomWindow,
} from '@/shared/kernel';

export type {
  ChartInstance,
  ChartOptions,
  SeriesOptions,
  AxisOptions,
  CaptionOptions,
  BackgroundOptions,
  LegendOptions,
  LegendItemOptions,
  LegendItemStyleOptions,
  LegendItemMarkerOptions,
  LegendMarkerOptions,
  LegendMarkerShape,
  LegendPlacement,
  LegendBackgroundOptions,
  GradientLegendOptions,
  TooltipOptions,
  HighlightOptions,
  OverlaysOptions,
  ZoomOptions,
  NavigatorOptions,
  CrosshairOptions,
  SyncOptions,
  ContextMenuOptions,
  AnimationOptions,
  FontsOptions,
  ChartState,
  LineSeriesOptions,
  BarSeriesOptions,
  AreaSeriesOptions,
  ScatterSeriesOptions,
  BubbleSeriesOptions,
  HistogramSeriesOptions,
  HistogramTooltipRendererParams,
  BinningOptions,
  BinEdge,
  BinRule,
  BinInclusive,
  BinOutliers,
  HistogramNormalize,
  HistogramNormalizeWithin,
  HistogramGroupMode,
  PieSeriesOptions,
  DonutSeriesOptions,
  RadarLineSeriesOptions,
  RadarAreaSeriesOptions,
  NightingaleSeriesOptions,
  RadialColumnSeriesOptions,
  RadialBarSeriesOptions,
  HeatmapSeriesOptions,
  RangeBarSeriesOptions,
  RangeAreaSeriesOptions,
  BoxPlotSeriesOptions,
  WaterfallSeriesOptions,
  FunnelSeriesOptions,
  ConeFunnelSeriesOptions,
  CandlestickSeriesOptions,
  OhlcSeriesOptions,
  TreemapSeriesOptions,
  SunburstSeriesOptions,
  PyramidSeriesOptions,
  SankeySeriesOptions,
  ChordSeriesOptions,
  RadialGaugeSeriesOptions,
  LinearGaugeSeriesOptions,
  LocaleOptions,
  AnnotationOptions,
  SelectionOptions,
  ChartListeners,
  NodeClickEvent,
  SelectionChangeEvent,
  NumberAxisOptions,
  CategoryAxisOptions,
  TimeAxisOptions,
  LogAxisOptions,
  OrdinalTimeAxisOptions,
  GroupedCategoryAxisOptions,
} from '@/app/chart-factory';
export { buildSparklineOptions } from '@/app/chart-factory';
export type { FinancialChartOptions, GaugeOptions, SparklineOptions } from '@/app/chart-factory';
export type { ThemeName, ThemeOptions, ThemeParams, ThemeAxisOptions, ResolvedTheme } from '@/app/themes';
export { THEME_NAMES, resolveTheme } from '@/app/themes';
export type * from '@/shared/options/primitives';
