/**
 * Full grafit entry point: all series and axes included.
 * Default modules are registered lazily (on the first create) — the module
 * stays free of side effects, but it statically references app/setup,
 * so the whole library ends up in the bundle. For a minimal bundle
 * use 'grafit-charts/core' + 'grafit-charts/modules'.
 */
import { buildCharts } from '@/app/chart-factory';
import { registerDefaultModules } from '@/app/setup';

export const Charts = buildCharts(registerDefaultModules);

export { register } from '@/app/registry';
export type {
  ChartModule,
  SeriesModule,
  AxisModule,
  TooltipContentData,
  TooltipHeading,
  TooltipRow,
  NodeRef,
  SelectedNode,
  ImperativeOptions,
  DomainAnchor,
  ZoomWindow,
} from '@/shared/kernel';
export * from './modules';

export type {
  ChartInstance,
  ChartOptions,
  SeriesOptions,
  AxisOptions,
  CaptionOptions,
  BackgroundOptions,
  LegendOptions,
  LegendItemOptions,
  LegendItemStyleOptions,
  LegendItemMarkerOptions,
  LegendMarkerOptions,
  LegendMarkerShape,
  LegendPlacement,
  LegendBackgroundOptions,
  GradientLegendOptions,
  TooltipOptions,
  HighlightOptions,
  OverlaysOptions,
  ZoomOptions,
  NavigatorOptions,
  CrosshairOptions,
  SyncOptions,
  ContextMenuOptions,
  AnimationOptions,
  FontsOptions,
  ChartState,
  LineSeriesOptions,
  BarSeriesOptions,
  AreaSeriesOptions,
  ScatterSeriesOptions,
  BubbleSeriesOptions,
  HistogramSeriesOptions,
  HistogramTooltipRendererParams,
  BinningOptions,
  BinEdge,
  BinRule,
  BinInclusive,
  BinOutliers,
  HistogramNormalize,
  HistogramNormalizeWithin,
  HistogramGroupMode,
  PieSeriesOptions,
  DonutSeriesOptions,
  RadarLineSeriesOptions,
  RadarAreaSeriesOptions,
  NightingaleSeriesOptions,
  RadialColumnSeriesOptions,
  RadialBarSeriesOptions,
  HeatmapSeriesOptions,
  RangeBarSeriesOptions,
  RangeAreaSeriesOptions,
  BoxPlotSeriesOptions,
  WaterfallSeriesOptions,
  FunnelSeriesOptions,
  ConeFunnelSeriesOptions,
  CandlestickSeriesOptions,
  OhlcSeriesOptions,
  TreemapSeriesOptions,
  SunburstSeriesOptions,
  PyramidSeriesOptions,
  SankeySeriesOptions,
  ChordSeriesOptions,
  RadialGaugeSeriesOptions,
  LinearGaugeSeriesOptions,
  LocaleOptions,
  AnnotationOptions,
  SelectionOptions,
  ChartListeners,
  NodeClickEvent,
  SelectionChangeEvent,
  NumberAxisOptions,
  CategoryAxisOptions,
  TimeAxisOptions,
  LogAxisOptions,
  OrdinalTimeAxisOptions,
  GroupedCategoryAxisOptions,
  GroupLabelOptions,
  GroupLabelFormatterParams,
  PolarAxesOptions,
  PolarAngleAxisOptions,
  PolarRadiusAxisOptions,
  PolarAxisLabelOptions,
  PolarAxisLabelParams,
  PolarAxisLineOptions,
  PolarAxisTitleOptions,
  PolarGridLineOptions,
} from '@/app/chart-factory';
export { buildSparklineOptions } from '@/app/chart-factory';
export type { FinancialChartOptions, GaugeOptions, SparklineOptions } from '@/app/chart-factory';
export type { ThemeName, ThemeOptions, ThemeParams, ThemeAxisOptions, ResolvedTheme } from '@/app/themes';
export { THEME_NAMES, resolveTheme } from '@/app/themes';
export type * from '@/shared/options/primitives';
